/-
Copyright (c) 2026 The critical-radius-five authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The critical-radius-five authors
-/
import Mathlib

/-!
# Two-disk compound symmetry groups: the definitions

This file contains the definitions on which the main theorem rests, and nothing else. They are
repeated verbatim in `Challenge.lean`; the comparator checks that the two copies elaborate to
identical kernel terms, so the theorem proved by this library is literally the statement of the
challenge.

Two closed disks of radius `r` are centred at `-1` and `1` in the complex plane. The generator `a`
turns the left disk clockwise by `2π/n` and fixes every point outside it; the generator `b` does
the same with the right disk. Where the two disks overlap the turns interfere, and the group they
generate, `GG n r`, may be finite or infinite. The critical radius `criticalRadius n` is the
supremum of the radii at which it is finite.

## Main definitions

* `CriticalRadiusFive.turn c r θ`: the permutation of `ℂ` that rotates the closed disk of radius
  `r` about `c` by the angle `θ` and fixes every point off the disk.
* `CriticalRadiusFive.genA n r`, `CriticalRadiusFive.genB n r`: the clockwise turns by `2π/n` of
  the disks about `-1` and about `1`.
* `CriticalRadiusFive.GG n r`: the subgroup of `Equiv.Perm ℂ` generated by the two turns.
* `CriticalRadiusFive.criticalRadius n`: the supremum of the radii `r` at which `GG n r` is finite.

## References

* R. Hearn, W. Kretschmer, T. Rokicki, B. Streeter, E. Vergo, *Two-Disk Compound Symmetry Groups*,
  arXiv:2302.12950.
-/

noncomputable section

open Complex

namespace CriticalRadiusFive

/-- The *turn* of the closed disk of radius `r` about `c` by the angle `θ`: the rotation
`z ↦ c + exp(iθ) (z - c)` on the disk, and the identity off it. It is a permutation of `ℂ`
because the rotation maps the disk onto itself. -/
def turn (c : ℂ) (r θ : ℝ) : Equiv.Perm ℂ where
  toFun z := if ‖z - c‖ ≤ r then c + exp (θ * I) * (z - c) else z
  invFun z := if ‖z - c‖ ≤ r then c + exp (-θ * I) * (z - c) else z
  left_inv z := by
    by_cases h : ‖z - c‖ ≤ r <;> simp [h, exp_neg]
  right_inv z := by
    by_cases h : ‖z - c‖ ≤ r <;> simp [h, exp_neg]

/-- The generator `a`: the clockwise turn by `2π/n` of the closed disk of radius `r` about `-1`,
that is `z ↦ exp(-2πi/n) (z + 1) - 1` on that disk. -/
def genA (n : ℕ) (r : ℝ) : Equiv.Perm ℂ := turn (-1) r (-(2 * Real.pi / n))

/-- The generator `b`: the clockwise turn by `2π/n` of the closed disk of radius `r` about `1`,
that is `z ↦ exp(-2πi/n) (z - 1) + 1` on that disk. -/
def genB (n : ℕ) (r : ℝ) : Equiv.Perm ℂ := turn 1 r (-(2 * Real.pi / n))

/-- The two-disk compound symmetry group `GG_n(r)`: the group of permutations of `ℂ` generated by
the two turns `genA n r` and `genB n r`. -/
def GG (n : ℕ) (r : ℝ) : Subgroup (Equiv.Perm ℂ) := Subgroup.closure {genA n r, genB n r}

/-- The critical radius of `GG n`: the supremum of the radii `r` at which `GG n r` is finite.
(As always in Mathlib, `sSup` of a set that is empty or unbounded above is `0`. For `n = 5` the set
is the interval `(-∞, √(3 + φ))`: this is the theorem `finite_GG_five_iff`.) -/
def criticalRadius (n : ℕ) : ℝ := sSup {r : ℝ | Finite (GG n r)}

end CriticalRadiusFive
