/-
Copyright (c) 2026 The critical-radius-five authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The critical-radius-five authors
-/
import CriticalRadiusFive.Basic

/-!
# Finiteness of `GG n r`: bounded orbits, and monotonicity in the radius

* `finite_of_encard_orbit_le` (**bounded orbits**): a group of permutations that is generated by a
  finite set and all of whose orbits have at most `N` points is finite. This is how finiteness is
  proved below the critical radius: every orbit is trapped in a finite set whose size depends on
  the radius only.
* `exists_mem_GG_apply_eq`, `orbit_subset_orbit_of_le`: enlarging the radius can only enlarge the
  orbits. The groups themselves are not nested — their generators are different permutations — but
  at any single point a generator either acts by the same rotation for both radii or not at all.
* `finite_GG_of_le`: consequently finiteness of `GG n r` is inherited by every smaller radius.
* `finite_GG_iff_of_forall_lt`, `criticalRadius_eq_of_forall_lt`: a radius at which the group is
  infinite, and below which it is always finite, is the critical radius; the group is finite
  exactly below it.
-/

noncomputable section

open Set MulAction

namespace CriticalRadiusFive

/-! ### Bounded orbits imply a finite group -/

section BoundedOrbits

variable {X : Type*}

/-- **Bounded orbits imply finiteness.** Let `G` be the group of permutations of `X` generated by a
finite set `s`. If every `G`-orbit has at most `N` points, then `G` is finite.

For each `x`, the action of `G` on the orbit of `x`, transported into `Equiv.Perm (Fin N)`, is a
homomorphism `ψ x : G →* Equiv.Perm (Fin N)`. It is determined by its values on the finitely many
generators, so only finitely many homomorphisms `ψ x` occur. Evaluating all of them embeds `G` into
a finite product of copies of `Equiv.Perm (Fin N)`: an element acting trivially on every orbit is
the identity. -/
theorem finite_of_encard_orbit_le {G : Subgroup (Equiv.Perm X)} {s : Set (Equiv.Perm X)}
    (hG : Subgroup.closure s = G) (hs : s.Finite) (N : ℕ)
    (hN : ∀ x : X, (orbit G x).encard ≤ N) : Finite G := by
  classical
  have hemb (x : X) : Nonempty (orbit G x ↪ Fin N) := by
    obtain ⟨hfin, hcard⟩ := encard_le_coe_iff_finite_ncard_le.1 (hN x)
    have := hfin.fintype
    refine Function.Embedding.nonempty_of_card_le ?_
    rwa [Fintype.card_fin, ← Nat.card_eq_fintype_card, Nat.card_coe_set_eq]
  -- The action on the orbit of `x`, transported to `Fin N`.
  let ψ (x : X) : G →* Equiv.Perm (Fin N) :=
    (Equiv.Perm.viaEmbeddingHom (hemb x).some).comp (toPermHom G (orbit G x))
  -- A homomorphism out of `G` is determined by its values on the generators.
  subst hG
  have hgen : Function.Injective fun (φ : Subgroup.closure s →* Equiv.Perm (Fin N)) (g : s) =>
      φ ⟨g, Subgroup.subset_closure g.2⟩ := by
    intro φ φ' h
    refine MonoidHom.eq_of_eqOn_dense Subgroup.closure_closure_coe_preimage fun g hg => ?_
    exact congrFun h ⟨g, hg⟩
  have : Finite s := hs.to_subtype
  have : Finite (range ψ) := Finite.of_injective _ (hgen.comp Subtype.val_injective)
  -- Evaluating all the `ψ x` embeds `G` into a finite product of copies of `Perm (Fin N)`.
  refine Finite.of_injective (fun g (φ : range ψ) => φ.1 g) fun g h hgh => ?_
  refine Subtype.ext (Equiv.ext fun x => ?_)
  have h₁ : ψ x g = ψ x h := congrFun hgh ⟨ψ x, x, rfl⟩
  exact congrArg Subtype.val congr($(Equiv.Perm.viaEmbeddingHom_injective _ h₁) ⟨x, mem_orbit_self x⟩)

end BoundedOrbits

variable {n : ℕ} {r r' : ℝ}

/-! ### Monotonicity in the radius -/

/-- At a given point, a turn of a disk acts either as the turn of any larger concentric disk or
not at all. -/
theorem turn_apply_eq_or (hr : r ≤ r') (c : ℂ) (θ : ℝ) (p : ℂ) :
    turn c r θ p = turn c r' θ p ∨ turn c r θ p = p := by
  by_cases h : ‖p - c‖ ≤ r
  · exact .inl (by rw [turn_apply_of_le h, turn_apply_of_le (h.trans hr)])
  · exact .inr (turn_apply_of_not_le h)

/-- **Pointwise monotonicity.** If `r ≤ r'`, every element of `GG n r` agrees at any given point
with some element of `GG n r'`. -/
theorem exists_mem_GG_apply_eq (hr : r ≤ r') {g : Equiv.Perm ℂ} (hg : g ∈ GG n r) (p : ℂ) :
    ∃ h ∈ GG n r', h p = g p := by
  induction hg using Subgroup.closure_induction generalizing p with
  | mem g hg =>
    obtain ⟨h, hh, c, rfl, rfl⟩ : ∃ h ∈ GG n r', ∃ c, g = turn c r (-(2 * Real.pi / n)) ∧
        h = turn c r' (-(2 * Real.pi / n)) := by
      rcases hg with rfl | rfl
      exacts [⟨_, genA_mem_GG n r', -1, rfl, rfl⟩, ⟨_, genB_mem_GG n r', 1, rfl, rfl⟩]
    rcases turn_apply_eq_or hr c _ p with h' | h'
    exacts [⟨_, hh, h'.symm⟩, ⟨1, one_mem _, h'.symm⟩]
  | one => exact ⟨1, one_mem _, rfl⟩
  | mul g g' _ _ ih ih' =>
    obtain ⟨h', hh', hp'⟩ := ih' p
    obtain ⟨h, hh, hp⟩ := ih (g' p)
    exact ⟨h * h', mul_mem hh hh', by simp [hp', hp]⟩
  | inv g _ ih =>
    obtain ⟨h, hh, hp⟩ := ih (g⁻¹ p)
    refine ⟨h⁻¹, inv_mem hh, ?_⟩
    rw [show g (g⁻¹ p) = p by simp] at hp
    rw [Equiv.Perm.inv_eq_iff_eq, hp]

/-- **Orbits grow with the radius.** -/
theorem orbit_subset_orbit_of_le (n : ℕ) (hr : r ≤ r') (p : ℂ) :
    orbit (GG n r) p ⊆ orbit (GG n r') p := by
  rintro _ ⟨g, rfl⟩
  obtain ⟨h, hh, hp⟩ := exists_mem_GG_apply_eq hr g.2 p
  exact ⟨⟨h, hh⟩, hp⟩

/-- An infinite orbit makes the group infinite. -/
theorem infinite_of_orbit_infinite {G : Subgroup (Equiv.Perm ℂ)} {p : ℂ}
    (h : (orbit G p).Infinite) : Infinite G := by
  by_contra hG
  rw [not_infinite_iff_finite] at hG
  exact h (finite_range fun g : G => g • p)

/-- **Finiteness is monotone in the radius.** If `GG n r'` is finite and `r ≤ r'`, then `GG n r`
is finite: its orbits lie in those of `GG n r'`, which have at most `|GG n r'|` points. -/
theorem finite_GG_of_le (hr : r ≤ r') (hfin : Finite (GG n r')) : Finite (GG n r) := by
  refine finite_of_encard_orbit_le rfl (toFinite {genA n r, genB n r}) (Nat.card (GG n r'))
    fun p => ?_
  calc (orbit (GG n r) p).encard ≤ (orbit (GG n r') p).encard :=
        encard_le_encard (orbit_subset_orbit_of_le n hr p)
    _ ≤ (univ : Set (GG n r')).encard := by
        rw [orbit, ← image_univ]
        exact encard_image_le _ _
    _ = Nat.card (GG n r') := by rw [encard_univ, ENat.card_eq_coe_natCard]

/-! ### The critical radius -/

/-- Off the disks nothing moves: at a negative radius both generators are the identity. -/
theorem GG_eq_bot_of_neg (hr : r < 0) : GG n r = ⊥ := by
  have h (c : ℂ) : turn c r (-(2 * Real.pi / n)) = 1 :=
    Equiv.ext fun z => turn_apply_of_not_le fun h => (norm_nonneg _).trans h |>.not_gt hr
  simp [GG, genA, genB, h]

/-- **The critical radius is a threshold.** If `GG n r` is finite for every `r < R` but infinite
at `R`, then it is finite exactly for `r < R`. -/
theorem finite_GG_iff_of_forall_lt {R : ℝ} (hfin : ∀ r < R, Finite (GG n r))
    (hinf : Infinite (GG n R)) (r : ℝ) : Finite (GG n r) ↔ r < R := by
  refine ⟨fun h => ?_, hfin r⟩
  by_contra hR
  have := finite_GG_of_le (not_lt.1 hR) h
  exact not_finite (GG n R)

/-- If `GG n r` is finite for every `r < R` but infinite at `R`, then `R` is the critical
radius. -/
theorem criticalRadius_eq_of_forall_lt {R : ℝ} (hfin : ∀ r < R, Finite (GG n r))
    (hinf : Infinite (GG n R)) : criticalRadius n = R := by
  have : {r : ℝ | Finite (GG n r)} = Iio R := ext (finite_GG_iff_of_forall_lt hfin hinf)
  rw [criticalRadius, this, csSup_Iio]

end CriticalRadiusFive
