import Verso
import VersoManual
import VersoBlueprint
import VersoBlueprint.Commands.Graph
import VersoBlueprint.Commands.Summary
import CriticalRadiusFiveBlueprint.Chapters.Setup
import CriticalRadiusFiveBlueprint.Chapters.UpperBound
import CriticalRadiusFiveBlueprint.Chapters.LowerBound
import CriticalRadiusFiveBlueprint.Chapters.MainTheorem

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "The critical radius of GG₅" =>

Two closed disks of radius $`r`, centred at $`-1` and $`+1` in the complex plane, can each be turned
clockwise by $`72^\circ`. The group $`G_5(r)` generated by the two turns is finite for small $`r`
and infinite, so that the puzzle _jumbles_, for large $`r`. This blueprint lays out a complete proof,
formalized in Lean 4 with Mathlib, that the threshold is

$$`r_c(5) = \sqrt{3 + \varphi} = 2.1489611417\ldots,`

where $`\varphi` is the golden ratio, the value conjectured by Hearn, Kretschmer, Rokicki, Streeter
and Vergo in [Two-Disk Compound Symmetry Groups](https://arxiv.org/abs/2302.12950). The first chapter
sets up the group and the critical radius. The second proves the upper bound: at
$`r = \sqrt{3+\varphi}` three words act on a chord through the origin as an irrational rotation.
The third proves the lower bound: below $`\sqrt{3+\varphi}` a lattice cut confines every orbit. The
last chapter puts the two together. Every statement links to its Lean declaration, and the
dependency graph and the progress summary at the end show how the pieces fit.

{include 0 CriticalRadiusFiveBlueprint.Chapters.Setup}
{include 0 CriticalRadiusFiveBlueprint.Chapters.UpperBound}
{include 0 CriticalRadiusFiveBlueprint.Chapters.LowerBound}
{include 0 CriticalRadiusFiveBlueprint.Chapters.MainTheorem}

{blueprint_graph}
{blueprint_summary}
