/-
Copyright (c) 2026 The critical-radius-five authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The critical-radius-five authors
-/
import Mathlib

/-!
# The critical radius of the two-disk group `GG₅`: the statement

This file is the trusted statement. It depends on Mathlib only and is meant to be read in full.

Two closed disks of radius `r` are centred at `-1` and `1` in the complex plane. The generator `a`
turns the left disk clockwise by `2π/n` and fixes every point outside it; the generator `b` does
the same with the right disk. `GG n r` is the group of permutations of the plane generated by `a`
and `b`, and `criticalRadius n` is the supremum of the radii at which it is finite
(Hearn, Kretschmer, Rokicki, Streeter, Vergo, *Two-Disk Compound Symmetry Groups*,
arXiv:2302.12950).

The theorems below state that for `n = 5` the group is finite exactly when `r < √(3 + φ)`, where
`φ = (1 + √5)/2` is the golden ratio, so that the critical radius is `√(3 + φ) = 2.1489611…`.

The definitions are copied verbatim, in the same order, from `CriticalRadiusFive/Defs.lean`, the
first module of the proof. The comparator (`comparator.json`) checks that the solution's
definitions are the same kernel terms as these and that its proofs of the two theorems use no
axioms beyond `propext`, `Classical.choice` and `Quot.sound`.
-/

noncomputable section

open Complex

namespace CriticalRadiusFive

/-- The *turn* of the closed disk of radius `r` about `c` by the angle `θ`: the rotation
`z ↦ c + exp(iθ) (z - c)` on the disk, and the identity off it. It is a permutation of `ℂ`
because the rotation maps the disk onto itself. -/
def turn (c : ℂ) (r θ : ℝ) : Equiv.Perm ℂ where
  toFun z := if ‖z - c‖ ≤ r then c + exp (θ * I) * (z - c) else z
  invFun z := if ‖z - c‖ ≤ r then c + exp (-θ * I) * (z - c) else z
  left_inv z := by
    by_cases h : ‖z - c‖ ≤ r <;> simp [h, exp_neg]
  right_inv z := by
    by_cases h : ‖z - c‖ ≤ r <;> simp [h, exp_neg]

/-- The generator `a`: the clockwise turn by `2π/n` of the closed disk of radius `r` about `-1`,
that is `z ↦ exp(-2πi/n) (z + 1) - 1` on that disk. -/
def genA (n : ℕ) (r : ℝ) : Equiv.Perm ℂ := turn (-1) r (-(2 * Real.pi / n))

/-- The generator `b`: the clockwise turn by `2π/n` of the closed disk of radius `r` about `1`,
that is `z ↦ exp(-2πi/n) (z - 1) + 1` on that disk. -/
def genB (n : ℕ) (r : ℝ) : Equiv.Perm ℂ := turn 1 r (-(2 * Real.pi / n))

/-- The two-disk compound symmetry group `GG_n(r)`: the group of permutations of `ℂ` generated by
the two turns `genA n r` and `genB n r`. -/
def GG (n : ℕ) (r : ℝ) : Subgroup (Equiv.Perm ℂ) := Subgroup.closure {genA n r, genB n r}

/-- The critical radius of `GG n`: the supremum of the radii `r` at which `GG n r` is finite.
(As always in Mathlib, `sSup` of a set that is empty or unbounded above is `0`. For `n = 5` the set
is the interval `(-∞, √(3 + φ))`: this is the theorem `finite_GG_five_iff`.) -/
def criticalRadius (n : ℕ) : ℝ := sSup {r : ℝ | Finite (GG n r)}

end CriticalRadiusFive

open CriticalRadiusFive
open scoped goldenRatio

/-- **`GG₅(r)` is finite exactly below `√(3 + φ)`.** -/
theorem finite_GG_five_iff (r : ℝ) : Finite (GG 5 r) ↔ r < √(3 + φ) := by
  sorry

/-- **The critical radius of `GG₅` is `√(3 + φ)`.** -/
theorem criticalRadius_five : criticalRadius 5 = √(3 + φ) := by
  sorry
