/-
Copyright (c) 2026 The critical-radius-five authors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The critical-radius-five authors
-/
import CriticalRadiusFive

/-!
# Reading guide: what the formal statement says

`Challenge.lean` states the theorem on top of five definitions (`turn`, `genA`, `genB`, `GG`,
`criticalRadius`). This file unfolds them, so that a reader can confirm that the formal statement
means what the informal one says, and restates the two theorems with `GG` and `criticalRadius`
unfolded (`genA` and `genB` stay folded; the lemmas below spell them out). Every proof here is
`rfl`, a one-line unfolding, or a direct appeal to the library; nothing new is proved.
-/

open Complex
open scoped goldenRatio

namespace CriticalRadiusFive

/-- A turn moves a point of its disk by the rotation about the centre and fixes every other
point. -/
theorem turn_apply_check (c : ℂ) (r θ : ℝ) (z : ℂ) :
    turn c r θ z = if ‖z - c‖ ≤ r then c + exp (θ * I) * (z - c) else z := rfl

/-- The generator `a` is the clockwise turn by `2π/n` of the closed disk of radius `r` about `-1`:
on that disk it is `z ↦ exp(-2πi/n) (z + 1) - 1`. -/
theorem genA_apply_check (n : ℕ) (r : ℝ) (z : ℂ) (hz : ‖z + 1‖ ≤ r) :
    genA n r z = exp (-(2 * Real.pi / n) * I) * (z + 1) - 1 := by
  simp only [genA, turn_apply_check, sub_neg_eq_add, hz, ite_true]; push_cast; ring

/-- The generator `b` is the clockwise turn by `2π/n` of the closed disk of radius `r` about `1`:
on that disk it is `z ↦ exp(-2πi/n) (z - 1) + 1`. -/
theorem genB_apply_check (n : ℕ) (r : ℝ) (z : ℂ) (hz : ‖z - 1‖ ≤ r) :
    genB n r z = exp (-(2 * Real.pi / n) * I) * (z - 1) + 1 := by
  simp only [genB, turn_apply_check, hz, ite_true]; push_cast; ring

/-- Off its disk, the generator `a` fixes the point. -/
theorem genA_apply_of_not_check (n : ℕ) (r : ℝ) (z : ℂ) (hz : ¬ ‖z + 1‖ ≤ r) : genA n r z = z := by
  simp [genA, turn_apply_check, hz]

/-- Off its disk, the generator `b` fixes the point. -/
theorem genB_apply_of_not_check (n : ℕ) (r : ℝ) (z : ℂ) (hz : ¬ ‖z - 1‖ ≤ r) : genB n r z = z := by
  simp [genB, turn_apply_check, hz]

/-- The group is the subgroup of permutations of the plane generated by the two turns. -/
theorem GG_check (n : ℕ) (r : ℝ) : GG n r = Subgroup.closure {genA n r, genB n r} := rfl

/-- The critical radius is the supremum of the finite radii. -/
theorem criticalRadius_check (n : ℕ) : criticalRadius n = sSup {r : ℝ | Finite (GG n r)} := rfl

/-- **The theorem, with `GG` unfolded:** the group generated by the two clockwise `72°` turns of
the disks of radius `r` about `∓1` is finite if and only if `r < √(3 + φ)`. -/
theorem finite_iff_check (r : ℝ) :
    Finite (Subgroup.closure {genA 5 r, genB 5 r}) ↔ r < √(3 + φ) :=
  finite_GG_five_iff r

/-- **The critical radius, with `GG` and `criticalRadius` unfolded.** -/
theorem criticalRadius_check_five :
    sSup {r : ℝ | Finite (Subgroup.closure {genA 5 r, genB 5 r})} = √(3 + φ) :=
  criticalRadius_five

end CriticalRadiusFive
