name = "CriticalRadiusFive"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["CriticalRadiusFive", "Challenge", "Solution", "Test"]
lintDriver = "batteries/runLinter"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "5ed2965256430c3649e86755f9576b54eca72435"

[[lean_lib]]
name = "CriticalRadiusFive"

[[lean_lib]]
name = "Challenge"
roots = ["Challenge"]

[[lean_lib]]
name = "Solution"
roots = ["Solution"]

[[lean_lib]]
name = "Test"
roots = ["Test"]
