import Verso
import VersoManual
import VersoBlueprint
import CriticalRadiusFive

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "The puzzle as a group" =>
%%%
tag := "chapter-setup"
file := "setup"
shortTitle := "Setup"
%%%

:::group "setup"
Setup
:::

Throughout, $`r` is a real number (the radius), $`D_- = \overline{D}(-1, r)` and
$`D_+ = \overline{D}(+1, r)` are the closed disks of radius $`r` about $`-1` and $`+1` in
$`\mathbb{C}`, $`\zeta = e^{2\pi i/5}`, and $`\varphi = (1+\sqrt5)/2` is the golden ratio. Words in
the turns are read from left to right: the first letter acts first, $`(ab)(z) = b(a(z))`.

:::definition "def:turns" (parent := "setup") (lean := "CriticalRadiusFive.turn, CriticalRadiusFive.genA, CriticalRadiusFive.genB")
*The two turns.* The left turn $`a` rotates $`D_-` clockwise by $`72^\circ` about $`-1` and fixes
every other point:

$$`a(z) = \zeta^{-1}(z+1) - 1 \ \text{ if } |z+1| \le r, \qquad a(z) = z \ \text{ otherwise};`

the right turn $`b` is the same about $`+1`: $`b(z) = \zeta^{-1}(z-1) + 1` if $`|z-1| \le r` and
$`b(z) = z` otherwise. Both are bijections of $`\mathbb{C}` (a rotation of a closed disk about its
centre is a bijection of the disk, and the turn is the identity outside it), so
$`a, b \in \operatorname{Perm}(\mathbb{C})`. For general $`n` the same definitions are made with
$`\zeta_n = e^{2\pi i/n}` in place of $`\zeta`.
:::

:::definition "def:group" (parent := "setup") (lean := "CriticalRadiusFive.GG") (uses := "def:turns")
*The group.* $`\mathrm{GG}_5(r)` is the subgroup of $`\operatorname{Perm}(\mathbb{C})` generated by
the two turns $`a, b` of {bpref "def:turns"}[]. A _position_ of the puzzle is an element of
$`\mathrm{GG}_5(r)`; the points $`g(p)`, $`g \in \mathrm{GG}_5(r)`, form the orbit
$`\mathrm{GG}_5(r)\cdot p` of $`p`. The puzzle _jumbles_ at radius $`r` if $`\mathrm{GG}_5(r)` is
infinite.
:::

:::definition "def:criticalRadius" (parent := "setup") (lean := "CriticalRadiusFive.criticalRadius") (uses := "def:group")
*The critical radius.* $`r_c(5) := \sup\,\{\, r \mid \mathrm{GG}_5(r) \text{ is finite} \,\}`, with
$`\mathrm{GG}_5(r)` as in {bpref "def:group"}[]. For general $`n`, $`r_c(n)` is defined in the same
way from the group generated by the turns by $`2\pi/n`.
:::

:::lemma_ "lemma:orbit-mono" (parent := "setup") (lean := "CriticalRadiusFive.exists_mem_GG_apply_eq, CriticalRadiusFive.orbit_subset_orbit_of_le")
*Orbits grow with the radius.* If $`r \le r'`, then every point reachable from $`p` in the group
of {uses "def:group"}[] at radius $`r` is reachable from $`p` at radius $`r'`:
$`\mathrm{GG}_5(r)\cdot p \subseteq \mathrm{GG}_5(r')\cdot p`.
:::

:::proof "lemma:orbit-mono"
A word acts on $`p` through a sequence of intermediate points, so it suffices to simulate a single
turn at a single point $`z`. If $`z` lies in the radius-$`r` disk of the turn, it lies in the
radius-$`r'` disk, where the radius-$`r'` turn acts on it in exactly the same way. Otherwise the
radius-$`r` turn fixes $`z`, and so does the identity of $`\mathrm{GG}_5(r')`. By induction along
the word, every element of $`\mathrm{GG}_5(r)` agrees at the point in question with some element of
$`\mathrm{GG}_5(r')`. The subtlety is that the larger turn may move points that the smaller one
fixes, so the group $`\mathrm{GG}_5(r)` is in general not a subgroup of $`\mathrm{GG}_5(r')`; this
is why the statement is about reachability, not about equality of words.
:::

:::theorem "thm:bounded-orbits" (parent := "setup") (lean := "CriticalRadiusFive.finite_of_encard_orbit_le")
*Bounded orbits imply a finite group.* Let $`\Gamma \le \operatorname{Perm}(X)` be generated by a
finite set $`S`, and suppose every $`\Gamma`-orbit in $`X` has at most $`N` elements. Then
$`\Gamma` is finite.
:::

:::proof "thm:bounded-orbits"
For $`x \in X` let $`\rho_x : \Gamma \to \operatorname{Perm}(\Gamma\cdot x)` be the restriction of
the action to the orbit of $`x`. Composing with an embedding
$`\Gamma\cdot x \hookrightarrow \{1,\dots,N\}` gives a homomorphism $`\sigma_x : \Gamma \to S_N`
with the same kernel. A homomorphism out of $`\Gamma = \langle S\rangle` is determined by its values
on $`S`, so $`x \mapsto \sigma_x|_S` takes values in the finite set of maps $`S \to S_N`; hence only
finitely many kernels $`\ker\rho_x` occur. Their intersection over all $`x` is trivial, since an
element that fixes every point of $`X` is the identity permutation. So the trivial subgroup is a
finite intersection of subgroups of finite index (each index is at most $`N!`), and therefore has
finite index: $`\Gamma` is finite.
:::

:::lemma_ "lemma:finite-mono" (parent := "setup") (lean := "CriticalRadiusFive.finite_GG_of_le")
*Finiteness is monotone in the radius.* If $`r \le r'` and $`\mathrm{GG}_5(r')` is finite, then
$`\mathrm{GG}_5(r)` is finite. Equivalently, if $`\mathrm{GG}_5(r)` is infinite, then
$`\mathrm{GG}_5(r')` is infinite for every $`r' \ge r`.
:::

:::proof "lemma:finite-mono"
Every orbit of $`\mathrm{GG}_5(r')` has at most $`|\mathrm{GG}_5(r')|` points. By
{uses "lemma:orbit-mono"}[] each orbit of $`\mathrm{GG}_5(r)` is contained in an orbit of
$`\mathrm{GG}_5(r')`, so the orbits of $`\mathrm{GG}_5(r)` are uniformly bounded. Since
$`\mathrm{GG}_5(r)` is generated by the two turns, {uses "thm:bounded-orbits"}[] shows that
$`\mathrm{GG}_5(r)` is finite.
:::

:::lemma_ "lemma:threshold" (parent := "setup") (lean := "CriticalRadiusFive.finite_GG_iff_of_forall_lt, CriticalRadiusFive.criticalRadius_eq_of_forall_lt") (uses := "def:criticalRadius")
*The critical radius is a threshold.* If $`\mathrm{GG}_5(r)` is finite for every $`r < R` and
infinite at $`R`, then it is finite exactly for $`r < R`, and $`r_c(5) = R`.
:::

:::proof "lemma:threshold"
If $`\mathrm{GG}_5(r)` were finite for some $`r \ge R`, then $`\mathrm{GG}_5(R)` would be finite by
{uses "lemma:finite-mono"}[]. So the radii with a finite group form $`(-\infty, R)`, whose supremum
is $`R`.
:::
