import Verso
import VersoManual
import VersoBlueprint
import CriticalRadiusFive

open Verso.Genre
open Verso.Genre.Manual
open Informal

#doc (Manual) "The puzzle as a group" =>
%%%
tag := "chapter-setup"
file := "setup"
shortTitle := "Setup"
%%%

:::group "setup"
Setup: the two-disk group and its critical radius
:::

Throughout, $`r` is a real number (the radius), $`D_- = \overline{D}(-1, r)` and
$`D_+ = \overline{D}(+1, r)` are the closed disks of radius $`r` about $`-1` and $`+1` in
$`\mathbb{C}`, $`\zeta = e^{2\pi i/5}`, and $`\varphi = (1+\sqrt5)/2` is the golden ratio. Words in
the turns are read from left to right: the first letter acts first, $`(ab)(z) = b(a(z))`.

:::definition "def:turns" (parent := "setup") (lean := "CriticalRadiusFive.turn, CriticalRadiusFive.genA, CriticalRadiusFive.genB")
*The two turns.* The left turn $`a` rotates $`D_-` clockwise by $`72^\circ` about $`-1` and fixes
every other point:

$$`a(z) = \zeta^{-1}(z+1) - 1 \ \text{ if } |z+1| \le r, \qquad a(z) = z \ \text{ otherwise};`

the right turn $`b` is the same about $`+1`: $`b(z) = \zeta^{-1}(z-1) + 1` if $`|z-1| \le r` and
$`b(z) = z` otherwise. Both are bijections of $`\mathbb{C}` (a rotation of a closed disk about its
centre is a bijection of the disk, and the turn is the identity outside it), so
$`a, b \in \operatorname{Perm}(\mathbb{C})`. For general $`n` the same definitions are made with
$`\zeta_n = e^{2\pi i/n}` in place of $`\zeta`.
:::

:::definition "def:group" (parent := "setup") (lean := "CriticalRadiusFive.GG")
*The group.* $`G_5(r)` is the subgroup of $`\operatorname{Perm}(\mathbb{C})` generated by the two
turns $`a, b` of {bpref "def:turns"}[]. A _position_ of the puzzle is an element of $`G_5(r)`; the
positions reachable from a point $`p` form its orbit $`G_5(r)\cdot p`. The puzzle _jumbles_ at
radius $`r` if $`G_5(r)` is infinite.
:::

:::definition "def:criticalRadius" (parent := "setup") (lean := "CriticalRadiusFive.criticalRadius")
*The critical radius.* $`r_c(5) := \sup\,\{\, r \mid G_5(r) \text{ is finite} \,\}`, with
$`G_5(r)` as in {bpref "def:group"}[]. For general $`n`, $`r_c(n)` is defined in the same way from
the group generated by the turns by $`2\pi/n`.
:::

:::lemma_ "lemma:orbit-mono" (parent := "setup") (lean := "CriticalRadiusFive.exists_mem_GG_apply_eq, CriticalRadiusFive.orbit_subset_orbit_of_le")
*Orbits grow with the radius.* If $`r \le r'`, then every point reachable from $`p` in
{uses "def:group"}[] at radius $`r` is reachable from $`p` at radius $`r'`:
$`G_5(r)\cdot p \subseteq G_5(r')\cdot p`.
:::

:::proof "lemma:orbit-mono"
A word acts on $`p` through a sequence of intermediate points, so it suffices to simulate a single
turn at a single point $`z`. If the radius-$`r` turn moves $`z`, then $`z` lies in its radius-$`r`
disk, hence in the radius-$`r'` disk, where the radius-$`r'` turn moves it in exactly the same
way. If the radius-$`r` turn fixes $`z` (because $`z` lies outside its disk), the identity of
$`G_5(r')` does the same. By induction along the word, every element of $`G_5(r)` agrees at the
point in question with some element of $`G_5(r')`. The subtlety is that the larger turn may move
points that the smaller one fixes, so the group $`G_5(r)` is not a subgroup of $`G_5(r')`; this
is why the statement is about reachability, not about equality of words.
:::

:::theorem "thm:T1" (parent := "setup") (lean := "CriticalRadiusFive.finite_of_encard_orbit_le")
*Bounded orbits imply a finite group.* Let $`G \le \operatorname{Perm}(X)` be generated by a finite
set $`S`, and suppose every $`G`-orbit in $`X` has at most $`N` elements. Then $`G` is finite.
:::

:::proof "thm:T1"
For $`x \in X` let $`\rho_x : G \to \operatorname{Perm}(G\cdot x)` be the restriction of the action
to the orbit of $`x`. Composing with an embedding $`G\cdot x \hookrightarrow \{1,\dots,N\}` gives a
homomorphism $`\sigma_x : G \to S_N` with the same kernel. A homomorphism out of
$`G = \langle S\rangle` is determined by its values on $`S`, so $`x \mapsto \sigma_x|_S` takes values
in the finite set of maps $`S \to S_N`; hence only finitely many kernels $`\ker\rho_x` occur. Their
intersection over all $`x` is trivial, since an element that fixes every point of $`X` is the
identity permutation. So the trivial subgroup is a finite intersection of subgroups of finite index
(each index is at most $`N!`), and therefore has finite index: $`G` is finite.
:::

:::lemma_ "lemma:finite-mono" (parent := "setup") (lean := "CriticalRadiusFive.finite_GG_of_le")
*Finiteness is monotone in the radius.* If $`r \le r'` and $`G_5(r')` is finite, then $`G_5(r)` is
finite. Equivalently, if $`G_5(r)` is infinite, then $`G_5(r')` is infinite for every $`r' \ge r`.
:::

:::proof "lemma:finite-mono"
Every orbit of $`G_5(r')` has at most $`|G_5(r')|` points. By {uses "lemma:orbit-mono"}[] each orbit
of $`G_5(r)` is contained in an orbit of $`G_5(r')`, so the orbits of $`G_5(r)` are uniformly
bounded. Since $`G_5(r)` is generated by the two turns, {uses "thm:T1"}[] shows that $`G_5(r)` is
finite.
:::

:::lemma_ "lemma:crit-upper" (parent := "setup") (lean := "CriticalRadiusFive.finite_GG_iff_of_forall_lt")
*An infinite group bounds the critical radius from above.* If $`G_5(r_0)` is infinite, then
$`r_c(5) \le r_0`, where $`r_c(5)` is {uses "def:criticalRadius"}[].
:::

:::proof "lemma:crit-upper"
By {uses "lemma:finite-mono"}[] every $`r \ge r_0` gives an infinite group, so
$`\{\, r \mid G_5(r) \text{ finite} \,\} \subseteq (-\infty, r_0)`, and its supremum is at most $`r_0`.
:::

:::lemma_ "lemma:crit-lower" (parent := "setup") (lean := "CriticalRadiusFive.criticalRadius_eq_of_forall_lt")
*Finite groups below a radius bound the critical radius from below.* If $`G_5(r)` is finite for
every $`r < r_0`, then $`r_0 \le r_c(5)`, where $`r_c(5)` is {uses "def:criticalRadius"}[].
:::

:::proof "lemma:crit-lower"
The set $`\{\, r \mid G_5(r) \text{ finite} \,\}` contains every $`r < r_0`, and it is bounded
above once some radius gives an infinite group, which {bpref "thm:upper"}[] supplies. Its supremum
is therefore a real number that is at least every $`r < r_0`, hence at least $`r_0`.
:::
